
title: Readings on Fascism
description: > # this means to ignore newlines until "baseurl:"
    A collection of resources on fascism and authoritarianism.
baseurl: "/fascism"
url: "https://kk4ead.github.io"
